# 有关pip conda Anaconda学习记录
## Anaconda环境相关

## pip相关

 1. raise ReadTimeoutError(self._pool, None, 'Read timed out.')
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
原因：网络不好
解决：重试；延长Timeout时间；换源
[https://blog.csdn.net/qq_38316655/article/details/81463917](https://blog.csdn.net/qq_38316655/article/details/81463917)转载

2. 

## conda相关 